### ISSUE TITLE
get-started/hello_world 编译失败

### ISSUE THREAD

**Issue by licaijing** [bekencorp/armino#8]
li@li-virtual-machine:~/armino$ make bk7256 PROJECT=examples/get-started/hello_world
$(PROJECT) is examples/get-started/hello_world
Traceback (most recent call last):
  File "/home/li/armino/tools/build_tools/compute_files_hash.py", line 83, in <module>
    tree = Node(sys.argv[1])
  File "/home/li/armino/tools/build_tools/compute_files_hash.py", line 65, in __init__
    self.node_hash = self.generate_file_hash(path)
  File "/home/li/armino/tools/build_tools/compute_files_hash.py", line 33, in generate_file_hash
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/li/armino/components/bk_libs/bk7256_examples/get-started/hello_world/libs'
build bk7256
Setting ARMINO_PATH environment variable: /home/li/armino
Executing action: set-target
Running cmake in directory /home/li/armino/build/hello_world/bk7256
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DBEKEN_PLATFORM=1 -DARMINO_SOC=bk7256 -DCCACHE_ENABLE=0 /home/li/armino/projects/examples/get-started/hello_world"...
-- Found Git: /usr/bin/git (found version "2.34.1")
-- LIB_HASH IS ""
-- use configured toolchain path: toolchain_v5.2.1/nds32le-elf-mculib-v5/bin
-- global toolchain file: /home/li/armino/middleware/soc/bk7256/toolchain-bk7256.cmake
-- The C compiler identification is GNU 10.4.0
-- The CXX compiler identification is GNU 10.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/li/armino/toolchain_v5.2.1/nds32le-elf-mculib-v5/bin/riscv32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/li/armino/toolchain_v5.2.1/nds32le-elf-mculib-v5/bin/riscv32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/li/armino/toolchain_v5.2.1/nds32le-elf-mculib-v5/bin/riscv32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Beken ARMINO components for target bk7256
/home/li/armino/build/hello_world/bk7256/kconfigs.in
/home/li/armino/build/hello_world/bk7256/components_kconfigs.in
/home/li/armino/build/hello_world/bk7256/kconfigs.in
/home/li/armino/build/hello_world/bk7256/middleware_kconfigs.in
/home/li/armino/build/hello_world/bk7256/kconfigs.in
/home/li/armino/build/hello_world/bk7256/projects_kconfigs.in
/home/li/armino/build/hello_world/bk7256/kconfigs.in
/home/li/armino/build/hello_world/bk7256/properties_kconfigs.in
/home/li/armino/build/hello_world/bk7256/kconfigs.in
/home/li/armino/build/hello_world/bk7256/extra_kconfigs.in
warning: AUD_TRAS_UAC_SPK_VOL_CTRL_MODE_STOP_UAC_TRAS (defined at /home/li/armino/components/demos/media/audio/aud_intf/Kconfig:156) has leading or trailing whitespace in its prompt
warning: AUD_TRAS_UAC_SPK_VOL_CTRL_MODE_MUTE (defined at /home/li/armino/components/demos/media/audio/aud_intf/Kconfig:161) has leading or trailing whitespace in its prompt
warning: OTA_HTTPS (defined at /home/li/armino/components/ota/Kconfig:17) has 'help' but empty help text
Loading defaults file /home/li/armino/middleware/soc/bk7256/bk7256.defconfig...
-- nds_ldsag_cmd execute success...
-- Adding linker script /home/li/armino/middleware/soc/bk7256/bk7256_bsp.ld
-- Include directory '/home/li/armino/properties/modules/btdm_5_2_rw/ble_pub/include/bk_private' is not a directory.
cat: /home/li/armino/components/bk_libs/bk7256_examples/get-started/hello_world/hash/toolchain_version.txt: No such file or directory
cat: /home/li/armino/components/bk_libs/bk7256_examples/get-started/hello_world/hash/libs_hash.txt: No such file or directory
CMake Error at /home/li/armino/components/bk_libs/CMakeLists.txt:37 (message):
  bk_libs or toolchain version verify failed, stop!!!

-- Include directory '/home/li/armino/properties/modules/aec' is not a directory.
-- Include directory '/home/li/armino/include/arch/compiler' is not a directory.
-- Include directory '/home/li/armino/include/modules/lvgl/src/gpu' is not a directory.
-- Include directory '/home/li/armino/components/demos/net/cs2p2p_middleware/include' is not a directory.
-- Include directory '/home/li/armino/components/demos/media/audio/mp3/include' is not a directory.
Found User C Module(s):
Check defconfig: /home/li/armino/middleware/soc/bk7256/bk7256.defconfig
-- Components: aac_decoder adc_key adpcm aec agora agora-iot-sdk ali_mqtt app arm9 at at_server aud aud_intf aud_ns aud_vad audio audio_asr audio_play audio_record av_demo base64 bk7256 bk_adapter bk_ate bk_ble bk_bt bk_cli bk_common bk_event bk_https bk_init bk_libs bk_log bk_netif bk_ps bk_rtos bk_startup bk_system bk_usb bk_vfs bk_websocket bk_wifi bluetooth cm33 cmsis common compal coredump cs2p2p cs2p2p_middleware dma2d doorbell driver easy_flash es8311 fatfs fft flac flashdb g711 h264 http i2s include iperf jrtplib key key_handle lcd_8080 lcd_qspi lcd_rgb littlefs lvgl_source lwip_intf_v2_0 lwip_intf_v2_1 main matter mbedtls media media_common micropython mp3 multimedia openssl opus os os_source ota part_table picture_display pm qcbor qrcodegen release riscv rott rsp saradc_intf sbc_decode security temp_detect touch usb user_driver utf8 video vnd_cal vnd_flash wanson webclient
-- Configuring incomplete, errors occurred!
See also "/home/li/armino/build/hello_world/bk7256/CMakeFiles/CMakeOutput.log".
See also "/home/li/armino/build/hello_world/bk7256/CMakeFiles/CMakeError.log".
cmake failed with exit code 1
make: *** [Makefile:125: bk7256] Error 2

请问怎么解决？

**Comment by zhouliacl** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/li/armino/components/bk_libs/bk7256_examples/get-started/hello_world/libs'
---- 这里没有找到库，你拷贝一份库过去应该就可以了
